export const SET_CURRENT_USER_LOGIN = 'SET_CURRENT_USER_LOGIN';
export const SET_CURRENT_USER_SIGNUP = 'SET_CURRENT_USER_SIGNUP';
export const SET_CURRENT_USER_ADD_NAME = 'SET_CURRENT_USER_ADD_NAME';
export const SET_CURRENT_USER_ADD_PROFILE_PIC = 'SET_CURRENT_USER_ADD_PROFILE_PIC';
export const SET_CURRENT_USER_SEARCH_BAR = 'SET_CURRENT_USER_SEARCH_BAR';
