export const SET_CURRENT_USER_LOGIN = 'SET_CURRENT_USER_LOGIN';
export const SET_CURRENT_USER_SIGNUP = 'SET_CURRENT_USER_SIGNUP';
export const SET_CURRENT_USER_LOGOUT = 'SET_CURRENT_USER_LOGOUT';
export const SET_CURRENT_USER_ADD_NAME = 'SET_CURRENT_USER_ADD_NAME';
export const SET_CURRENT_USER_ADD_PROFILE_PIC = 'SET_CURRENT_USER_ADD_PROFILE_PIC';
export const SET_CURRENT_USER_SEARCH_BAR = 'SET_CURRENT_USER_SEARCH_BAR';
export const SET_CURRENT_COORDS = 'SET_CURRENT_COORDS';
export const SET_CURRENT_USER_ADD_PROIMG = 'SET_CURRENT_USER_ADD_PROIMG';
export const SET_SEARCH_RESULT_LIST = 'SET_SEARCH_RESULT_LIST';
export const SET_SHOW_SEARCH_RESULT = 'SET_SHOW_SEARCH_RESULT';
export const SET_DESCRIPTION_ARRAY = 'SET_DESCRIPTION_ARRAY';


